store/main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', home, name='bardStore'),
    path('category/<int:category_id>/', products, name='category'),
    path('category/<int:category_id>/page/<int:page_number>/', products, name='category_paginator'),
    path('page/<int:page_number>/', products, name='paginator'),
    path('products/', products, name='products'),
    path('product/<int:product_id>/', product, name='product'),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('profile/', user_profile, name='user_profile'),
    path('orders/', user_orders, name='user_orders'),
    path('favorites/', user_favorites, name='user_favorites'),
    path('change_password/', user_password, name='user_password'),
    path('cart/', cart, name='cart'),
    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
]

store/main/models.py
from django.db import models

from users.models import User


class ProductCategory(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    SIZE_CHOICES = [
        ('XS', 'XS'),
        ('S', 'S'),
        ('M', 'M'),
        ('L', 'L'),
        ('XL', 'XL')
    ]
    name = models.CharField(max_length=128, verbose_name='Название')
    brand = models.CharField(max_length=128, null=True, blank=True, verbose_name='Бренд')
    description = models.TextField(verbose_name='Описание')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена')
    discount = models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True, verbose_name='Скидка')
    size = models.CharField(max_length=2, choices=SIZE_CHOICES, null=True, blank=True, verbose_name='Размер')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    image_1 = models.ImageField(upload_to='products_images/', verbose_name='1 картинка')
    image_2 = models.ImageField(upload_to='products_images/', null=True, blank=True, verbose_name='2 картинка')
    image_3 = models.ImageField(upload_to='products_images/', null=True, blank=True, verbose_name='3 картинка')
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE, verbose_name='Категория')

    def discount_price(self):
        if self.discount is not None:
            return self.price - (self.discount / 100) * self.price
        return self.price

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'Products'


    def __str__(self):
        return self.name


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='Пользователь')
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE, verbose_name='Товар')
    size = models.CharField(max_length=2, choices=Product.SIZE_CHOICES, null=True, blank=True, verbose_name='Размер')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт: {self.product.name}'
    
    def sum(self):
        return self.product.price * self.quantity
    
    def discount_sum(self):
        discount = self.product.discount
        if discount is not None and discount > 0:
            discounted_price = self.product.price * (1 - discount / 100)
            return discounted_price * self.quantity
        else:
            return self.product.price * self.quantity
    

store/main/views.py
from django.db.models import Q

from django.shortcuts import render, HttpResponseRedirect
from django.core.paginator import Paginator
from django.contrib import messages
from django.urls import reverse


from .models import Product, ProductCategory
from users.forms import CartForm, QuestionsForm

# Create your views here.
def home(request):
    if request.method == 'POST':
        form = QuestionsForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Ваш вопрос успешно отправлен!')
            return HttpResponseRedirect(reverse('main:bardStore'))
        else:
            print('error')
    else:
        form = QuestionsForm()
    context = {
        'title': 'Bard Store',
        'form': form
    }
    return render(request, 'main/index.html', context)


def products(request, category_id=None, page_number=1):
    categories = ProductCategory.objects.all()
    products = Product.objects.all()

    # Фильтрация по категории
    if category_id:
        products = products.filter(category_id=category_id)

    # Обработка поискового запроса
    search_query = request.GET.get('s')
    if search_query:
        search_query = search_query.capitalize()
        products = products.filter(Q(name__icontains=search_query) | Q(name__iexact=search_query))

    per_page = 4
    paginator = Paginator(products, per_page)
    products_paginator = paginator.page(page_number)

    context = {
        'products': products_paginator,
        'categories': categories,
        'current_page': page_number,
        'category_id': category_id,
        'search_query': search_query,
    }
    return render(request, 'main/products.html', context)


def product(request, product_id):
    form = CartForm()
    product = Product.objects.get(id=product_id)
    context = {
        'product': product,
        'form': form
    }
    return render(request, 'main/product.html', context)

store/main/templates/main/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'vendor/css/style.css' %}">

    <script src="{% static 'vendor/js/carousel.js' %}" defer></script>
    <title>Document</title>
</head>
<body>
    <header>
        <div class="header_wrapper">
            <nav class="navigation">
                <ul class="links">
                    <a href="{% url 'main:products' %}">Каталог</a>
                    <a href="#about-us">О нас</a>
                </ul>
                <div class="logo">
                    <a href="#">
                        <img src="{% static 'vendor/img/svg_icons/logo.png' %}" alt="logo">
                        <h1>Bard Store</h1>
                    </a>
                </div>
                <div class="profile_items">
                    <a href="{% url 'users:user_profile' %}">
                        <img src="{% static 'vendor/img/svg_icons/user.svg' %}" alt="user_icon">
                    </a>
                    <a href="{% url 'users:cart' %}">
                        <img src="{% static 'vendor/img/svg_icons/shopping-cart.svg' %}" alt="user_icon">
                    </a>
                </div>
            </nav>
        </div>
    </header>
    <main>
        <div class="title_wrapper">
            <div class="title">
                <div class="title-text">
                    <h1>
                        Одежда, которая заставляет вас чувствовать себя уверенно
                    </h1>
                </div>
                <a id="about-us" class="start-btn" href="#start">
                    Начать покупки
                </a>
            </div>
        </div>
        <div class="about-us">
            <div class="aboutus-block">
                <h2 class="h2-title">О нас</h2>
                <div class="aboutus-text">
                    Мы предлагаем широкий выбор одежды для мужчин, женщин и детей. У нас есть все, что вам нужно, чтобы выглядеть и чувствовать себя уверенно, независимо от вашего стиля или бюджета. Мы верим, что одежда должна быть не только стильной, но и удобной. Мы предлагаем только одежду из высококачественных материалов, которая будет хорошо сидеть на вас и будет комфортной в носке.
                </div>
            </div>
        </div>
        <div class="service">
            <h2 class="h2-title">Наш сервис предоставляет</h2>
            <div class="slideshow-container">

                <!-- Full-width images with number and caption text -->
                <div class="mySlides fade">
                  <div class="numbertext">1 / 3</div>
                  <img src="{% static 'vendor/img/slider_images/slide-1.jpg' %}" style="width:100%">
                  <div class="text">Высокое качество</div>
                </div>
              
                <div class="mySlides fade">
                  <div class="numbertext">2 / 3</div>
                  <img src="{% static 'vendor/img/slider_images/slide-2.jpg' %}" style="width:100%">
                  <div class="text">Широкий выбор одежды</div>
                </div>
              
                <div class="mySlides fade">
                  <div class="numbertext">3 / 3</div>
                  <img src="{% static 'vendor/img/slider_images/slide-3.jpg' %}" style="width:100%">
                  <div class="text">Доступные цены</div>
                </div>
              
                <!-- Next and previous buttons -->
                <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                <a class="next" onclick="plusSlides(1)">&#10095;</a>
            </div>
            <br>
              
              <!-- The dots/circles -->
            <div style="text-align:center">
                <span class="dot" onclick="currentSlide(1)"></span>
                <span class="dot" onclick="currentSlide(2)"></span>
                <span class="dot" onclick="currentSlide(3)"></span>
            </div>
        </div>
        <div class="goods">
            <h2 id="start" class="h2-title">Магазин</h2>
            <div class="goods-block">
                <div class="product-card">
                    <a href="#">
                        <img src="{% static 'vendor/img/product_iamges/1.jfif' %}" alt="img">
                    </a>
                    <div class="product-content">
                        <h3 class="product-name">Название</h3>
                        <div class="price-block">
                            <span class="price">10000 ₽</span>
                            <span class="discount-price">10000 ₽</span>
                        </div>
                        <a href="#" class="card-btn">В корзину</a>
                    </div>
                </div>
                <div class="product-card">
                    <a href="#">
                        <img src="{% static 'vendor/img/product_iamges/2.jfif' %}" alt="img">
                    </a>
                    <div class="product-content">
                        <h3 class="product-name">Название</h3>
                        <div class="price-block">
                            <span class="price">10000 ₽</span>
                            <span class="discount-price">10000 ₽</span>
                        </div>
                        <a href="#" class="card-btn">В корзину</a>
                    </div>
                </div>
                <div class="product-card">
                    <a href="#">
                        <img src="{% static 'vendor/img/product_iamges/3.jfif' %}" alt="img">
                    </a>
                    <div class="product-content">
                        <h3 class="product-name">Название</h3>
                        <div class="price-block">
                            <span class="price">10000 ₽</span>
                            <span class="discount-price">10000 ₽</span>
                        </div>
                        <a href="#" class="card-btn">В корзину</a>
                    </div>
                </div>
                <div class="product-card">
                    <a href="#">
                        <img src="{% static 'vendor/img/product_iamges/4.jfif' %}" alt="img">
                    </a>
                    <div class="product-content">
                        <h3 class="product-name">Название</h3>
                        <div class="price-block">
                            <span class="price">10000 ₽</span>
                            <span class="discount-price">10000 ₽</span>
                        </div>
                        <a href="#" class="card-btn">В корзину</a>
                    </div>
                </div>
                <div class="product-card">
                    <a href="#">
                        <img src="{% static 'vendor/img/product_iamges/5.jfif' %}" alt="img">
                    </a>
                    <div class="product-content">
                        <h3 class="product-name">Название</h3>
                        <div class="price-block">
                            <span class="price">10000 ₽</span>
                            <span class="discount-price">10000 ₽</span>
                        </div>
                        <a href="#" class="card-btn">В корзину</a>
                    </div>
                </div>
                <div class="product-card">
                    <a href="#">
                        <img src="{% static 'vendor/img/product_iamges/6.jfif' %}" alt="img">
                    </a>
                    <div class="product-content">
                        <h3 class="product-name">Название</h3>
                        <div class="price-block">
                            <span class="price">10000 ₽</span>
                            <span class="discount-price">10000 ₽</span>
                        </div>
                        <a href="#" class="card-btn">В корзину</a>
                    </div>
                </div>
                <div class="product-card">
                    <a href="#">
                        <img src="{% static 'vendor/img/product_iamges/7.jfif' %}" alt="img">
                    </a>
                    <div class="product-content">
                        <h3 class="product-name">Название</h3>
                        <div class="price-block">
                            <span class="price">10000 ₽</span>
                            <span class="discount-price">10000 ₽</span>
                        </div>
                        <a href="#" class="card-btn">В корзину</a>
                    </div>
                </div>
                <div class="product-card">
                    <a href="#">
                        <img src="{% static 'vendor/img/product_iamges/8.jfif' %}" alt="img">
                    </a>
                    <div class="product-content">
                        <h3 class="product-name">Название</h3>
                        <div class="price-block">
                            <span class="price">10000 ₽</span>
                            <span class="discount-price">10000 ₽</span>
                        </div>
                        <a href="#" class="card-btn">В корзину</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="question_wrapper">
            <div class="question-block">
                <div class="left-question-block">
                    <h2>Есть вопросы?</h2>
                    <p>Если у вас есть какие-либо вопросы, пожалуйста, не стесняйтесь обращаться к нам.</p>
                    <p>Что бы задать вопрос вы должны заполнить форму и отправить.</p>
                    <p>Мы постараемся ответить на ваш вопрос как можно быстрее.</p>
                    <p>Максимальное время ожидания 24 часа. </p>
                    <div class="also">
                        <h3>Также вы можете связятся с нами ниже</h3>
                        <a href="#contacts" class="contact-btn">Связяться с нами</a>
                    </div>
                </div>
                <div class="right-question-block">
                    <h2>Написать нам</h2>
                    <form class="question-form" action="{% url 'main:bardStore' %}" method="POST">
                        {% csrf_token %}
                        {{ form.name }}
                        {{ form.email }}
                        {{ form.Text }}
                        <button type="submit">Отправить</button>
                    </form>
                    {% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                        style="margin-top: 50px;">
                            {{ form.errors }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </main>
    <footer>
        <div class="left-footer-block">
            <div class="logo">
                <a href="#">
                    <img src="{% static 'vendor/img/svg_icons/footer-logo.png' %}" alt="logo">
                    <h1 class="footer-h1">Bard Store</h1>
                </a>
            </div>
            <div id="contacts" class="contacts">
                <h4>Наши контакты</h4>
                <p>+996 (999) 34-45-34</p>
                <p>Московская 34 / Ибраимова</p>
                <p>example@gmail.com</p>
            </div>
        </div>
        <div class="rigth-footer-block">
            <div class="for-buyers">
                <h5>КАТАЛОГ</h5>
                <a href="#">НОВИНКИ</a>
                <a href="#">ЖЕНСКАЯ ОДЕЖДА</a>
                <a href="#">МУЖСКАЯ ОДЕЖДА</a>
                <a href="#">ДЕТСКИЕ</a>
                <a href="#">СКИДКИ</a>
            </div>
            <div class="for-buyers">
                <h5>ПОКУПАТЕЛЯМ</h5>
                <a href="#">О КОМПАНИИ</a>
                <a href="#">ДОСТАВКА И ОПЛАТА</a>
                <a href="#">НЕ ПОЛУЧЕН ТОВАР</a>
                <a href="#">КОНТАКТЫ</a>
                <a href="#">ТАБЛИЦА РАЗМЕРОВ</a>
            </div>
            <div class="socials">
                <h5>СОЦИАЛЬНЫЕ СЕТИ</h5>
                <div class="social-items">
                    <a href="#"><img src="{% static 'vendor/img/svg_icons/telegram.png' %}" alt="facebook"></a>
                    <a href="#"><img src="{% static 'vendor/img/svg_icons/instagram.png' %}" alt="instagram"></a>
                    <a href="#"><img src="{% static 'vendor/img/svg_icons/tiktok.png' %}" alt="tiktok"></a>
                    <a href="#"><img src="{% static 'vendor/img/svg_icons/whatsapp.png' %}" alt="whatsapp"></a>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

store/main/templates/main/products.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'vendor/css/products.css' %}">

    <script src="{% static 'vendor/js/slider.js' %}" defer></script>
    <script src="{% static 'vendor/js/script.js' %}" defer></script>
    <title>Document</title>
</head>
<body>
    <header>
        <div class="header_wrapper">
            <nav class="navigation">
                <ul class="links">
                    <a href="{% url 'main:bardStore' %}">Главная</a>
                    <a href="{% url 'main:bardStore' %}#about-us">О нас</a>
                </ul>
                <div class="logo">
                    <a href="#">
                        <img src="{% static 'vendor/img/svg_icons/logo.png' %}" alt="logo">
                        <h1>Bard Store</h1>
                    </a>
                </div>
                <div class="profile_items">
                    <a href="{% url 'users:user_profile' %}">
                        <img src="{% static 'vendor/img/svg_icons/user.svg' %}" alt="user_icon">
                    </a>
                    <a href="{% url 'users:cart' %}">
                        <img src="{% static 'vendor/img/svg_icons/shopping-cart.svg' %}" alt="user_icon">
                    </a>
                </div>
            </nav>
        </div>
    </header>
    <main>
        <div class="main_wrapper">
            <ul id="slides">
                <li class="slide showing"></li>
                <li class="slide"></li>
                <li class="slide"></li>
                <li class="slide"></li>
                <li class="slide"></li>
            </ul>
            <div class="container">
                <nav class="nav">
                    <form class="search-form" action="{% url 'main:products' %}" method="get">
                        <input name="s" placeholder="Искать..." type="search" value="{% if search_query %}{{ search_query }}{% endif %}">
                        <button type="submit">Поиск</button>
                    </form>
                </nav>
                <div class="block-content">
                    <div class="row">
                        <div class="category">
                            <h4 class="h4">КАТЕГОРИИ</h4>

                            <div class="category-items">
                                <ul>
                                    <a  class="cat-item" href="{% url 'main:products' %}">Все категории</a>
                                    {% for category in categories %}
                                    <a  class="cat-item" href="{% url 'main:category' category.id %}">{{ category }}</a>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="goods">
                        <div class="filter-block">
                            <button onclick="myFunction()" class="dropbtn">
                            </button>
                            <div id="myDropdown" class="dropdown-content">
                                <a href="#">Сортировать по названию</a>
                                <a href="#">Сортировать по цене</a>
                            </div>
                        </div>
                        <div class="goods-block">
                            {% for product in products %}
                            <div class="product-card">
                                <a href="{% url 'main:product' product.id %}">
                                    <img src="{{ product.image_1.url }}" alt="img">
                                </a>
                                <div class="product-content">
                                    <h3 class="product-name">{{ product.name }}</h3>
                                    <div class="price-block">
                                        <span>{{ product.discount_price }} ₽</span>
                                        {% if product.discount %}
                                        <span class="price">-{{ product.discount|floatformat:0 }}%</span>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            <nav class="pagination">
                                <a href="{% if products.has_previous %}{% if category_id %}{% url 'main:category_paginator' category_id=category_id page_number=products.previous_page_number %}{% else %}{% url 'main:paginator' page_number=products.previous_page_number %}{% endif %}{% else %}#{% endif %}" class="{% if not products.has_previous %}disabled{% endif %}">«</a>
                                {% for page in products.paginator.page_range %}
                                    {% if category_id %}
                                        <a href="{% url 'main:category_paginator' category_id=category_id page_number=page %}" class="{% if page == current_page %}active{% endif %}">{{ page }}</a>
                                    {% else %}
                                        <a href="{% url 'main:paginator' page_number=page %}" class="{% if page == current_page %}active{% endif %}">{{ page }}</a>
                                    {% endif %}
                                {% endfor %}
                                <a href="{% if products.has_next %}{% if category_id %}{% url 'main:category_paginator' category_id=category_id page_number=products.next_page_number %}{% else %}{% url 'main:paginator' page_number=products.next_page_number %}{% endif %}{% else %}#{% endif %}" class="{% if not products.has_next %}disabled{% endif %}">»</a>
                            </nav>                     
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <footer>
        <div class="left-footer-block">
            <div class="logo">
                <a href="#">
                    <img src="{% static 'vendor/img/svg_icons/footer-logo.png' %}" alt="logo">
                    <h1 class="footer-h1">Bard Store</h1>
                </a>
            </div>
            <div id="contacts" class="contacts">
                <h4>Наши контакты</h4>
                <p>+996 (999) 34-45-34</p>
                <p>Московская 34 / Ибраимова</p>
                <p>example@gmail.com</p>
            </div>
        </div>
        <div class="rigth-footer-block">
            <div class="for-buyers">
                <h5>КАТАЛОГ</h5>
                <a href="#">НОВИНКИ</a>
                <a href="#">ЖЕНСКАЯ ОДЕЖДА</a>
                <a href="#">МУЖСКАЯ ОДЕЖДА</a>
                <a href="#">ДЕТСКИЕ</a>
                <a href="#">СКИДКИ</a>
            </div>
            <div class="for-buyers">
                <h5>ПОКУПАТЕЛЯМ</h5>
                <a href="#">О КОМПАНИИ</a>
                <a href="#">ДОСТАВКА И ОПЛАТА</a>
                <a href="#">НЕ ПОЛУЧЕН ТОВАР</a>
                <a href="#">КОНТАКТЫ</a>
                <a href="#">ТАБЛИЦА РАЗМЕРОВ</a>
            </div>
            <div class="socials">
                <h5>СОЦИАЛЬНЫЕ СЕТИ</h5>
                <div class="social-items">
                    <a href="#"><img src="{% static 'vendor/img/svg_icons/telegram.png' %}" alt="facebook"></a>
                    <a href="#"><img src="{% static 'vendor/img/svg_icons/instagram.png' %}" alt="instagram"></a>
                    <a href="#"><img src="{% static 'vendor/img/svg_icons/tiktok.png' %}" alt="tiktok"></a>
                    <a href="#"><img src="{% static 'vendor/img/svg_icons/whatsapp.png' %}" alt="whatsapp"></a>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>