store/main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', home, name='bardStore'),
    path('category/<int:category_id>/', products, name='category'),
    path('category/<int:category_id>/page/<int:page_number>/', products, name='category_paginator'),
    path('page/<int:page_number>/', products, name='paginator'),
    path('products/', products, name='products'),
    path('product/<int:product_id>/', product, name='product'),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('profile/', user_profile, name='user_profile'),
    path('orders/', user_orders, name='user_orders'),
    path('favorites/', user_favorites, name='user_favorites'),
    path('change_password/', user_password, name='user_password'),
    path('cart/', cart, name='cart'),
    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
]

store/cart/models.py
from django.db import models

# Create your models here.

store/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    SEX_CHOICES = [
        ('M', 'Мужчина'),
        ('FM', 'Женщина'),
        ('A', 'Другой'),
    ]
    phone_number = models.CharField(max_length=19)
    date_of_birth = models.CharField(max_length=10, null=True, blank=True)
    sex = models.CharField(max_length=10, choices=SEX_CHOICES, null=True, blank=True)


    def __str__(self):
        return self.username
    

class Questions(models.Model):
    name = models.CharField(max_length=128, verbose_name='Имя')
    email = models.EmailField(max_length=128, verbose_name='Почта')
    Text = models.TextField(verbose_name='Текст')

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'question'
        verbose_name_plural = 'Questions'
    

store/users/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserCreationForm, UserChangeForm)


from .models import User, Questions


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-input',
            'placeholder': 'Введите имя пользователя',
        }
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-input',
            'placeholder': 'Введите пароль',
        }
    )) 

    class Meta:
        model = User
        fields = ('username', 'password',)



class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-input',
            'placeholder': 'Введите имя пользователя',
        }
    ))
    phone_number = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-input input-width',
            'placeholder': 'Номер телефона',
            'id': 'phone-number'
        }
    ))
    email = forms.CharField(widget=forms.EmailInput(
        attrs={
            'class': 'form-input input-width',
            'placeholder': 'Введите эл. почту',
        }
    ))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-input',
            'placeholder': 'Введите пароль',
        }
    ))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-input',
            'placeholder': 'Подтвердите пароль',
        }
    ))
    checkbox = forms.BooleanField(widget=forms.CheckboxInput(
        attrs={
            'class': 'checkbox',
        }
    ))

    class Meta:
        model = User
        fields = ['username', 'phone_number', 'email', 'password1', 'password2']



class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-input',
            'placeholder': 'Имя пользователя',
        }
    ))
    phone_number = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-input input-width',
            'placeholder': 'Номер телефона',
            'id': 'phone-number'
        }
    ))
    email = forms.CharField(widget=forms.EmailInput(
        attrs={
            'class': 'form-input input-width',
            'placeholder': 'эл. почта',
        }
    ))
    date_of_birth = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-input date-input',
            'placeholder': 'ДЕНЬ/МЕСЯЦ/ГОД',
        }
    ))

    GENDER_CHOICES = (
        ('M', 'Мужчина'),
        ('FM', 'Женщина'),
        ('A', 'Другой'),
    )
    sex = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect())

    class Meta:
        model = User
        fields = ['username', 'phone_number', 'email', 'date_of_birth', 'sex']


class CartForm(forms.Form):
    SIZE_CHOICES = [
        ('XS', 'XS'),
        ('S', 'S'),
        ('M', 'M'),
        ('L', 'L'),
        ('XL', 'XL')
    ]
    size = forms.ChoiceField(choices=SIZE_CHOICES, widget=forms.RadioSelect(
    ))
    quantity = forms.IntegerField(min_value=1, max_value=10, widget=forms.NumberInput(
        attrs = {
            "readonly": None,
            'value': '1'
        }
    ))

class QuestionsForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder': 'Ваше имя',
        }
    ))
    email = forms.CharField(widget=forms.EmailInput(
        attrs={
            'placeholder': 'Ваш e-mail',
        }
    ))
    Text = forms.CharField(widget=forms.Textarea(
        attrs={
            'placeholder': 'Ваш вопрос',
        }
    ))

    class Meta:
        model = Questions
        fields = ['name', 'email', 'Text']

store/cart/views.py
from django.shortcuts import render

# Create your views here.

store/users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth, messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required


from .forms import UserLoginForm, UserRegisterForm, UserProfileForm, CartForm

from main.models import Product, Basket



def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Регистрация прошла успешно!')
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegisterForm()
    context = {
        'form': form,
        'title': 'Store',
    }
    return render(request, 'users/register.html', context)


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('main:bardStore'))
    else:
        form = UserLoginForm()
    context = {
        'form': form,
        'title': 'Store-Login'
    }

    return render(request, 'users/login.html', context)



@login_required
def user_profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:bardStore'))
        else:
            print(form.errors)
    else:
        form = UserProfileForm(instance=request.user)
    context = {
        'form': form,
        'title': 'Store-profile',
    }
    return render(request, 'users/profile.html', context)


@login_required
def user_orders(request):
    return render(request, 'users/orders.html')


@login_required
def user_favorites(request):
    return render(request, 'users/favorites.html')


@login_required
def user_password(request):
    return render(request, 'users/change_password.html')


@login_required
def cart(request):
    baskets = Basket.objects.filter(user=request.user)
    total_sum_products = sum(basket.sum() for basket in baskets)
    discount_total_sum = sum(basket.discount_sum() for basket in baskets)
    if discount_total_sum == 0:
        total_sum = 0
    else:
        total_sum = discount_total_sum + 200
    context = {
        'baskets': baskets,
        'total_sum_products': total_sum_products,
        'discount_total_sum': discount_total_sum,
        'total_sum': total_sum,
    }

    return render(request, 'users/cart.html', context)


@login_required
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    
    if request.method == 'POST':
        form = CartForm(request.POST)
        if form.is_valid():
            size = form.cleaned_data['size']
            quantity = form.cleaned_data['quantity']
            baskets = Basket.objects.filter(user=request.user, product=product, size=size)

            if baskets.exists():
                basket = baskets.first()
                basket.quantity += quantity
                basket.save()
            else:
                Basket.objects.create(user=request.user, product=product, size=size, quantity=quantity)

            return HttpResponseRedirect(request.META['HTTP_REFERER'])
    else:
        form = CartForm()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

store/users/templates/users/base-authentification.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'vendor/css/register-login.css' %}">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'vendor/js/jquery.maskedinput.js' %}"></script>
    <script src="{% static 'vendor/js/phone-input.js' %}"></script>
    <title>Document</title>
</head>
<body>
    <div class="goback-block">
        <a class="goback-btn" href="{% url 'main:bardStore' %}">Вернуться</a>
    </div>
    {% block content %}
    {% endblock %}
    </div>
    <footer>
        <div class="left-footer-block">
            <div class="logo">
                <a href="#">
                    <img src="{% static 'vendor/img/svg_icons/footer-logo.png' %}" alt="logo">
                    <h1 class="footer-h1">Bard Store</h1>
                </a>
            </div>
            <div id="contacts" class="contacts">
                <h4>Наши контакты</h4>
                <p>+996 (999) 34-45-34</p>
                <p>Московская 34 / Ибраимова</p>
                <p>example@gmail.com</p>
            </div>
        </div>
        <div class="rigth-footer-block">
            <div class="for-buyers">
                <h5>КАТАЛОГ</h5>
                <a href="#">НОВИНКИ</a>
                <a href="#">ЖЕНСКАЯ ОДЕЖДА</a>
                <a href="#">МУЖСКАЯ ОДЕЖДА</a>
                <a href="#">ДЕТСКИЕ</a>
                <a href="#">СКИДКИ</a>
            </div>
            <div class="for-buyers">
                <h5>ПОКУПАТЕЛЯМ</h5>
                <a href="#">О КОМПАНИИ</a>
                <a href="#">ДОСТАВКА И ОПЛАТА</a>
                <a href="#">НЕ ПОЛУЧЕН ТОВАР</a>
                <a href="#">КОНТАКТЫ</a>
                <a href="#">ТАБЛИЦА РАЗМЕРОВ</a>
            </div>
            <div class="socials">
                <h5>СОЦИАЛЬНЫЕ СЕТИ</h5>
                <div class="social-items">
                    <a href="#"><img src="{% static 'vendor/img/svg_icons/telegram.png' %}" alt="facebook"></a>
                    <a href="#"><img src="{% static 'vendor/img/svg_icons/instagram.png' %}" alt="instagram"></a>
                    <a href="#"><img src="{% static 'vendor/img/svg_icons/tiktok.png' %}" alt="tiktok"></a>
                    <a href="#"><img src="{% static 'vendor/img/svg_icons/whatsapp.png' %}" alt="whatsapp"></a>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

store/users/templates/users/base-profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css-js %}
    {% endblock %}
    <title>Document</title>
</head>
<body>
    <header>
        <div class="header_wrapper">
            <nav class="navigation">
                <ul class="links">
                    <a href="{% url 'main:products' %}">Каталог</a>
                    <a href="{% url 'main:bardStore' %}">Главная</a>
                </ul>
                <div class="logo">
                    <a href="#">
                        <img src="{% static 'vendor/img/svg_icons/logo.png' %}" alt="logo">
                        <h1>Bard Store</h1>
                    </a>
                </div>
                <div class="profile_items">
                    <a href="{% url 'users:user_profile' %}">
                        <img src="{% static 'vendor/img/svg_icons/user.svg' %}" alt="user_icon">
                    </a>
                    <a href="{% url 'users:cart' %}">
                        <img src="{% static 'vendor/img/svg_icons/shopping-cart.svg' %}" alt="user_icon">
                    </a>
                </div>
            </nav>
        </div>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <div class="left-footer-block">
            <div class="logo">
                <a href="#">
                    <img src="{% static 'vendor/img/svg_icons/footer-logo.png' %}" alt="logo">
                    <h1 class="footer-h1">Bard Store</h1>
                </a>
            </div>
            <div id="contacts" class="contacts">
                <h4>Наши контакты</h4>
                <p>+996 (999) 34-45-34</p>
                <p>Московская 34 / Ибраимова</p>
                <p>example@gmail.com</p>
            </div>
        </div>
        <div class="rigth-footer-block">
            <div class="for-buyers">
                <h5>КАТАЛОГ</h5>
                <a href="#">НОВИНКИ</a>
                <a href="#">ЖЕНСКАЯ ОДЕЖДА</a>
                <a href="#">МУЖСКАЯ ОДЕЖДА</a>
                <a href="#">ДЕТСКИЕ</a>
                <a href="#">СКИДКИ</a>
            </div>
            <div class="for-buyers">
                <h5>ПОКУПАТЕЛЯМ</h5>
                <a href="#">О КОМПАНИИ</a>
                <a href="#">ДОСТАВКА И ОПЛАТА</a>
                <a href="#">НЕ ПОЛУЧЕН ТОВАР</a>
                <a href="#">КОНТАКТЫ</a>
                <a href="#">ТАБЛИЦА РАЗМЕРОВ</a>
            </div>
            <div class="socials">
                <h5>СОЦИАЛЬНЫЕ СЕТИ</h5>
                <div class="social-items">
                    <a href="#"><img src="{% static 'vendor/img/svg_icons/telegram.png' %}" alt="facebook"></a>
                    <a href="#"><img src="{% static 'vendor/img/svg_icons/instagram.png' %}" alt="instagram"></a>
                    <a href="#"><img src="{% static 'vendor/img/svg_icons/tiktok.png' %}" alt="tiktok"></a>
                    <a href="#"><img src="{% static 'vendor/img/svg_icons/whatsapp.png' %}" alt="whatsapp"></a>
                </div>
            </div>
        </div>
    </footer>
    {% block script %}
    {% endblock %}
</body>
</html>

store/users/templates/users/cart.html
{% extends 'users/base-profile.html' %}
{% load static %}


{% block css-js %}
<link rel="stylesheet" href="{% static 'vendor/css/cart.css' %}">
{% endblock %}


{% block content %}
<section>
    <div class="main_wrapper">
        {% if cart %}
        <h1 class="cart-title">Корзина</h1>
        {% else %}
        <h1 class="cart-title">Корзина пуста</h1>
        {% endif %}
        <div class="cart-container">
            <div class="cart-block">
                {% for c in baskets %}
                <div class="product">
                    <a href="#">
                        <img src="{{ c.product.image_1.url }}" alt="img">
                    </a>
                    <div class="product-content">
                        <div class="col-1">
                            <a href="#"><h3>{{ c.product.name }}</h3></a>
                            <span class="gray">{{ c.product.description|truncatechars:50 }}</span>
                            <div class="col-1-price">
                                <span class="product-discount gray">{{ c.sum }} ₽</span>
                                <span class="product-price">{{ c.discount_sum|floatformat:2 }} ₽</span>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="size-block">
                                <span class="gray">Размер</span>
                                <span class="bold">{{ c.size }}</span>
                            </div>
                            <div class="size-block">
                                <span class="gray">Количество</span>
                                <span class="bold">{{ c.quantity }}</span>
                            </div>
                        </div>
                        <div class="col-3">
                            <a href="{% url 'users:basket_remove' c.id %}"><img src="{% static 'vendor/img/svg_icons/trash.svg' %}" alt="delete"></a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="order-container">
                <div class="row">
                    <h2>Общая сумма</h2>
                    <div class="order-items">
                        <div class="item">
                            <span>Товары</span>
                            <span>{{ total_sum_products }} ₽</span>
                        </div>
                        <div class="item">
                            <span>Доставка</span>
                            <span>200 ₽</span>
                        </div>
                        <div class="item discount">
                            <span>Цена со скидкой</span>
                            <span>{{ discount_total_sum|floatformat:2 }} ₽</span>
                        </div>
                        <div class="item total-price">
                            <span>Итого к оплате</span>
                            <span>{{ total_sum }}</span>
                        </div>
                        <a class="checkout-btn" href="#">ПОДТВЕРДИТЬ</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

store/users/templates/users/change_password.html
{% extends 'users/base-profile.html' %}
{% load static %}

{% block css-js %}
<link rel="stylesheet" href="{% static 'vendor/css/profile.css' %}">
{% endblock %}



{% block content %}
<section>
    <div class="main_wrapper">
        <div class="row-container">
            <div class="row">
                <h2>Добро пожаловать Пользователь!</h2>
                <div class="nav_menu">
                    <a class="nav_item" href="{% url 'users:user_profile' %}"><img src="{% static 'vendor/img/svg_icons/user.svg' %}" alt="img"><span>Персональные данные</span></a>
                    <a class="nav_item" href="{% url 'users:user_orders' %}"><img src="{% static 'vendor/img/svg_icons/package.svg' %}" alt="img"><span>Покупки</span></a>
                    <a class="nav_item" href="{% url 'users:user_favorites' %}"><img src="{% static 'vendor/img/svg_icons/heart.svg' %}" alt="img"><span>Избранные</span></a>
                    <a class="nav_item active" href="{% url 'users:user_password' %}"><img src="{% static 'vendor/img/svg_icons/lock.svg' %}" alt="img"><span>Изменить пароль</span></a>
                </div>
            </div>
        </div>
        <div class="nav_content">
            <h1>Персональные данные</h1>
            <form class="form" action="{% url 'users:user_profile' %}" method="post">
                {% csrf_token %}
                <h5>СТАРЫЙ ПАРОЛЬ</h5>
                <input class="form-input" type="password">
                <br>
                <h5>НОВЫЙ ПАРОЛЬ</h5>
                <input class="form-input" type="password">
                <button class="form-btn" type="submit">Сохранить изменения</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}

store/users/templates/users/favorites.html
{% extends 'users/base-profile.html' %}
{% load static %}

{% block css-js %}
<link rel="stylesheet" href="{% static 'vendor/css/profile.css' %}">
{% endblock %}



{% block content %}
<section>
    <div class="main_wrapper">
        <div class="row-container">
            <div class="row">
                <h2>Добро пожаловать Пользователь!</h2>
                <div class="nav_menu">
                    <a class="nav_item" href="{% url 'users:user_profile' %}"><img src="{% static 'vendor/img/svg_icons/user.svg' %}" alt="img"><span>Персональные данные</span></a>
                    <a class="nav_item" href="{% url 'users:user_orders' %}"><img src="{% static 'vendor/img/svg_icons/package.svg' %}" alt="img"><span>Покупки</span></a>
                    <a class="nav_item active" href="{% url 'users:user_favorites' %}"><img src="{% static 'vendor/img/svg_icons/heart.svg' %}" alt="img"><span>Избранные</span></a>
                    <a class="nav_item" href="{% url 'users:user_password' %}"><img src="{% static 'vendor/img/svg_icons/lock.svg' %}" alt="img"><span>Изменить пароль</span></a>
                </div>
            </div>
        </div>
        <div class="nav_content">
            <h1>Избранные</h1>
            <div class="favorite_container">
                <div class="product-card">
                    <a href="#">
                        <img src="{% static 'vendor/img/product_iamges/8.jfif' %}" alt="img">
                    </a>
                    <div class="card-content">
                        <h3 class="product-name">Название</h3>
                        <div class="price-block">
                            <span class="price">10000 ₽</span>
                            <span class="discount-price">10000 ₽</span>
                        </div>
                        <a class="favorite-btn" href="#">Удалить из избранного</a>
                    </div>
                </div>
                <div class="product-card">
                    <a href="#">
                        <img src="{% static 'vendor/img/product_iamges/1.jfif' %}" alt="img">
                    </a>
                    <div class="card-content">
                        <h3 class="product-name">Название</h3>
                        <div class="price-block">
                            <span class="price">10000 ₽</span>
                            <span class="discount-price">10000 ₽</span>
                        </div>
                        <a class="favorite-btn" href="#">Удалить из избранного</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

store/users/templates/users/login.html
{% extends 'users/base-authentification.html' %}

{% block content %}
<div class="register-block">
    <div class="form-block">
        <h1>Вход</h1>
        <form class="form" action="{% url 'users:login' %}" method="POST">
            {% csrf_token %}
            {{ form.username }}
            {{ form.password }}
            <button class="form-btn" type="submit">Войти</button>
            <p class="form-link">Нужен аккаунт? <a href="{% url 'users:register' %}">Зарегистрироваться</a></p>
        </form>
    </div>
</div>
{% endblock %}

store/users/templates/users/orders.html
{% extends 'users/base-profile.html' %}
{% load static %}

{% block css-js %}
<link rel="stylesheet" href="{% static 'vendor/css/profile.css' %}">
{% endblock %}



{% block content %}
<section>
    <div class="main_wrapper">
        <div class="row-container">
            <div class="row">
                <h2>Добро пожаловать Пользователь!</h2>
                <div class="nav_menu">
                    <a class="nav_item" href="{% url 'users:user_profile' %}"><img src="{% static 'vendor/img/svg_icons/user.svg' %}" alt="img"><span>Персональные данные</span></a>
                    <a class="nav_item active" href="#"><img src="{% static 'vendor/img/svg_icons/package.svg' %}" alt="img"><span>Покупки</span></a>
                    <a class="nav_item" href="{% url 'users:user_favorites' %}"><img src="{% static 'vendor/img/svg_icons/heart.svg' %}" alt="img"><span>Избранные</span></a>
                    <a class="nav_item" href="{% url 'users:user_password' %}"><img src="{% static 'vendor/img/svg_icons/lock.svg' %}" alt="img"><span>Изменить пароль</span></a>
                </div>
            </div>
        </div>
        <div class="nav_content">
            <h1>Покупки</h1>
            <div class="order_container">
                <div class="order">
                    <h2>Заказ №76894502</h2>
                    <div class="order-data">
                        <div class="order-col">
                            <h4>Заказ</h4>
                            <span>№76894502</span>
                        </div>
                        <div class="order-col">
                            <h4>Дата оформления</h4>
                            <span>23 Апрель 2019</span>
                        </div>
                        <div class="order-col">
                            <h4>Итоговая цена</h4>
                            <span>18 600 ₽</span>
                        </div>
                        <div class="order-col">
                            <h4>Статус</h4>
                            <span>Оплачен</span>
                        </div>
                        <div class="order-col col-btn" style="border: none;">
                            <a href="#" class="order-btn">Подробнее</a>
                        </div>
                    </div>
                </div>
                <div class="order">
                    <h2>Заказ №12494502</h2>
                    <div class="order-data">
                        <div class="order-col">
                            <h4>Заказ</h4>
                            <span>№12494502</span>
                        </div>
                        <div class="order-col">
                            <h4>Дата оформления</h4>
                            <span>23 Апрель 2019</span>
                        </div>
                        <div class="order-col">
                            <h4>Итоговая цена</h4>
                            <span>12300 ₽</span>
                        </div>
                        <div class="order-col">
                            <h4>Статус</h4>
                            <span>В пути</span>
                        </div>
                        <div class="order-col col-btn" style="border: none;">
                            <a href="#" class="order-btn">Подробнее</a>
                        </div>
                    </div>
                </div>
                <div class="order">
                    <h2>Заказ №72134502</h2>
                    <div class="order-data">
                        <div class="order-col">
                            <h4>Заказ</h4>
                            <span>№72134502</span>
                        </div>
                        <div class="order-col">
                            <h4>Дата оформления</h4>
                            <span>23 Апрель 2019</span>
                        </div>
                        <div class="order-col">
                            <h4>Итоговая цена</h4>
                            <span>12000 ₽</span>
                        </div>
                        <div class="order-col">
                            <h4>Статус</h4>
                            <span>Доставлен</span>
                        </div>
                        <div class="order-col col-btn" style="border: none;">
                            <a href="#" class="order-btn">Подробнее</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

store/users/templates/users/profile.html
{% extends 'users/base-profile.html' %}
{% load static %}

{% block css-js %}
<link rel="stylesheet" href="{% static 'vendor/css/profile.css' %}">

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'vendor/js/jquery.maskedinput.js' %}"></script>
<script src="{% static 'vendor/js/phone-input.js' %}"></script>
{% endblock %}

{% block content %}
<section>
    <div class="main_wrapper">
        <div class="row-container">
            <div class="row">
                <h2>Добро пожаловать Пользователь!</h2>
                <div class="nav_menu">
                    <a class="nav_item active" href="#"><img src="{% static 'vendor/img/svg_icons/user.svg' %}" alt="img"><span>Персональные данные</span></a>
                    <a class="nav_item" href="{% url 'users:user_orders' %}"><img src="{% static 'vendor/img/svg_icons/package.svg' %}" alt="img"><span>Покупки</span></a>
                    <a class="nav_item" href="{% url 'users:user_favorites' %}"><img src="{% static 'vendor/img/svg_icons/heart.svg' %}" alt="img"><span>Избранные</span></a>
                    <a class="nav_item" href="{% url 'users:user_password' %}"><img src="{% static 'vendor/img/svg_icons/lock.svg' %}" alt="img"><span>Изменить пароль</span></a>
                </div>
            </div>
        </div>
        <div class="nav_content">
            <h1>Персональные данные</h1>
            <form class="form" action="{% url 'users:user_profile' %}" method="post">
                {% csrf_token %}
                <h5>ИМЯ ПОЛЬЗОВАТЕЛЯ</h5>
                {{ form.username }}
                <div class="phone-email-container">
                    {{ form.phone_number }}
                    {{ form.email }}                </div>
                <h5>ДАТА РОЖДЕНИЯ (необязательно)</h5>
                {{ form.date_of_birth }}
                <div class="gender-container">
                    <h5>ПОЛ (необязательно)</h5>
                    <div class="gender-container">
                        <div class="gender-items">
                            {% for radio in form.sex %}
                            <div class="form_radio">
                                {{ radio.tag }}
                                <label class="gender" for="{{ radio.id_for_label }}">{{ radio.choice_label }}</label>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <button class="form-btn" type="submit">Сохранить изменения</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}